# Versi API
apiVersion: v1
# service karsajobs-ui
kind: Service
metadata:
  name: karsajobs-ui-service
  labels:
    app: frontend
spec:
  ports:
  - port: 8000
  selector:
    app: frontend
  type: NodePort
