# Versi API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-backend
  labels:
    app: karsajobs
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-backend
  template:
    metadata:
      labels:
        app: karsajobs-backend
    spec:
      containers:
      - name: karsajobs-backend
        image: ghcr.io/ekoariaw8301/karsajobs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        # APP_PORT dengan nilai “8080”
        - name: APP_PORT
          value: '8080'
        - name: MONGO_HOST
          # MONGO_HOST dengan nilai yang diambil dari MongoDB Service  
          value: mongo-service
        - name: MONGO_USER
          # MONGO_USER dengan nilai yang diambil dari MongoDB Secret
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: MONGO_ROOT_USERNAME
        - name: MONGO_PASS
          # MONGO_PASS dengan nilai yang diambil dari MongoDB Secret 
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: MONGO_ROOT_PASSWORD
