#create headless service mangodb will port 27017
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: database
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: database
